baseURL = "https://rgartneraudios.github.io/archivo-editorial-site/"
languageCode = 'es'
title = 'RGartner Audios Podcast Editorial'
theme = 'PaperMod'
canonifyURLs = false

[pagination]
  pagerSize = 10
  path = "page"
  
defaultContentLanguage = 'es'

[languages]
[languages.es]
  languageName = 'Espa√±ol'
  weight = 1

[params]
  env = 'production'
  defaultTheme = 'dark'
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  mainSections = ["posts"]
